return {
  show_first_indent_level = false,
  show_end_of_line = true,
  -- show_current_context_start = true,
  -- space_char_blankline = " ",
  filetype_exclude = {
    "aerial",
    "alpha",
    "cpp",
    "dashboard",
    "help",
    "neo-tree",
    "neogitstatus",
    "NvimTree",
    "packer",
    -- "rust",
    "startify",
    "Trouble",
  },
}
