require("nvim-lastplace").setup {
  lastplace_ignore_buftype = { "quickfix", "nofile", "help", "terminal", "lspinfo" },
  lastplace_ignore_filetype = {
    "dashboard",
    "DiffviewFiles",
    "gitcommit",
    "gitrebase",
    "hgcommit",
    "mason",
    "neo-tree",
    "Neogitcommit",
    "NeogitCommitMessage",
    "NeogitPopup",
    "neogitstatus",
    "NvimTree",
    "packer",
    "startify",
    "svn",
    "Trouble",
  },
  lastplace_open_folds = true,
}
