return {
  after = "nvim-cmp",
  ft = {
    "asciidoc",
    "changelog",
    "context",
    "DiffviewFiles",
    "gitcommit",
    "Neogitcommit",
    "NeogitCommit",
    "NeogitCommitMessage",
    "lsp_markdown",
    "mail",
    "markdown",
    "rst",
    "rtf",
    "tex",
    "texinfo",
    "text",
    "txt",
  },
  config = function() astronvim.add_user_cmp_source "emoji" end,
}
