return {
  after = { nil },
  -- requires = { "nvim-treesitter/nvim-treesitter" },
  wants = "nvim-treesitter",
  ft = {
    "html",
    "javascript",
    "markdown",
    "php",
    "typescript",
    "typescriptreact",
    "vue",
    "xml",
    -- "glimmer",
    -- "handlebars",
    -- "hbs",
    -- "javascriptreact",
    -- "jsx",
    -- "rescript",
    -- "svelte",
    -- "tsx",
  },
}
