return {
  -- after = { nil },
  requires = { "nvim-treesitter/nvim-treesitter" },
  ft = {
    -- "glimmer",
    -- "handlebars",
    -- "hbs",
    "html",
    "javascript",
    -- "javascriptreact",
    -- "jsx",
    "markdown",
    "php",
    -- "rescript",
    -- "svelte",
    -- "tsx",
    "typescript",
    "typescriptreact",
    "vue",
    "xml",
  },
}
