-- vim: ft=lua:foldmarker=(((,))):foldmethod=marker:foldlevel=0:shiftwidth=2:softtabstop=2:tabstop=2

-- vimscript plugins (((

-- ["ilyachur/cmake4vim"] = require "user.plugins.cmake_for_vim", -- Vim plugin for CMake projects
-- ["ekalinin/Dockerfile.vim"] = require "user.plugins.dockerfile_vim", -- Vim syntax file & snippets for Docker's Dockerfile
-- ["bfrg/vim-cmakecache-syntax"] = require "user.plugins.cmakecache_syntax", -- Vim syntax file for CMakeCache.txt files generated by CMake

-- )))

-- lua plugins (((

-- ["Civitasv/cmake-tools.nvim"] = require "user.plugins.cmake_tools", -- CMake integration in Neovim
-- ["hrsh7th/cmp-calc"] = require "user.plugins.cmp_calc", -- nvim-cmp source for math calculation
-- ["hrsh7th/cmp-omni"] = require "user.plugins.cmp_omni", -- nvim-cmp source for omnifunc
-- ["akinsho/git-conflict.nvim"] = require "user.plugins.git_conflict", -- Visualise & resolve merge conflicts
-- ["ellisonleao/glow.nvim"] = { cmd = { "Glow", "GlowInstall" } }, -- A markdown preview directly in your neovim
-- ["jbyuki/nabla.nvim"] = require "user.plugins.nabla_nvim", -- Take your scientific notes in Neovim
-- ["nvim-neotest/neotest"] = require "user.plugins.nvim_neotest", -- An extensible framework for interacting with tests within NeoVim.
-- ["nvim-neotest/neotest-python"] = { ft = "python" }, -- Neotest adapter for python. Supports Pytest and unittest test files.
-- ["catppuccin/nvim"] = require "user.plugins.catppuccin_nvim", -- Soothing pastel theme for Neovim
-- ["Canop/nvim-bacon"] = { ft = "rust" }, -- bacon's companion for neovim
-- ["mfussenegger/nvim-dap"] = require "user.plugins.nvim_dap", -- Debug Adapter Protocol client implementation
-- ["rcarriga/nvim-dap-ui"] = require "user.plugins.nvim_dapui", -- A UI for nvim-dap
-- ["theHamsta/nvim-dap-virtual-text"] = require "user.plugins.nvim_dap_virtual_text", -- slow!
-- ["https://gitlab.com/yorickpeterse/nvim-dd"] = require "user.plugins.nvim_dd", -- Deferring of NeoVim diagnostics
-- ["kevinhwang91/nvim-hlslens"] = require "user.plugins.nvim_hlslens", -- A hlsearch Lens for Neovim
-- ["sitiom/nvim-numbertoggle"] = require "user.plugins.nvim_numbertoggle", -- Auto-toggle b/w rel & abs line nos
-- { "eddiebergman/nvim-treesitter-pyfold", after = { "nvim-treesitter" }, ft = "python" }, -- Sane Python folding
-- ["nvim-treesitter/nvim-treesitter-refactor"] = { after = "nvim-treesitter" }, -- Treesitter refactor module
-- ["nvim-treesitter/nvim-treesitter-textobjects"] = { after = "nvim-treesitter" },
-- ["s1n7ax/nvim-window-picker"] = {}, -- Prompts to pick a window & returns its window id
-- ["jbyuki/one-small-step-for-vimkind"] = {}, -- Debug adapter for Neovim plugins
-- ["Weissle/persistent-breakpoints.nvim"] = require "user.plugins.persistent-breakpoints",
-- ["ahmedkhalf/project.nvim"] = require "user.plugins.project", -- The superior project management solution for nvim
-- ["SantinoKeupp/telescope-cmake4vim.nvim"] = require "user.plugins.telescope_cmakeforvim",
-- ["nvim-telescope/telescope-symbols.nvim"] = require "user.plugins.telescope_symbols",

-- )))
