M = {}

M.kind_icons = {
  -- Class = "",
  -- Class = " ",
  -- Class = "",
  -- Color = " ",
  -- Color = "",
  -- Constant = "",
  -- Constant = " ",
  -- Constant = "",
  -- Constant = "",
  -- Constructor = "",
  -- Enum = " ",
  -- Enum = "",
  -- EnumMember = " ",
  -- Event = " ",
  -- Event = "",
  -- Field = " ",
  -- Field = "",
  -- File = " ",
  -- File = "",
  -- Folder = " ",
  -- Folder = "",
  -- Interface = " ",
  -- Interface = "ﰮ",
  -- Keyword = " ",
  -- Keyword = "",
  -- Module = " ",
  -- Module = "",
  -- Operator = " ",
  -- Property = "",
  -- Property = " ",
  -- Reference = " ",
  -- Reference = "",
  -- Snippet = " ",
  -- Struct = " ",
  -- Struct = "",
  -- Struct = "" ,
  -- Text = "",
  -- Text = "",
  -- TypeParameter = " ",
  -- TypeParameter = "",
  -- Unit = " ",
  -- Unit = "",
  -- Unit = "塞",
  -- Value = " ",
  -- Variable = " ",
  -- Variable = "",
  Array = "",
  Boolean = "⊨",
  Class = "ﴯ",
  Color = "",
  Constant = "",
  Constructor = "",
  Enum = "了",
  EnumMember = "",
  Event = "",
  Field = "ﰠ",
  File = "",
  Folder = "",
  Function = "",
  Interface = "",
  Key = "",
  Keyword = "",
  Method = "",
  Module = "",
  Namespace = "",
  Null = "NULL",
  Number = "#",
  Object = "⦿",
  Operator = "",
  Package = "",
  Property = "",
  Reference = "",
  Snippet = "",
  String = "𝓐",
  Struct = "פּ",
  Text = "",
  TypeParameter = "",
  Unit = "",
  Value = "",
  Variable = "",
}

-- M.lsp_servers = {
--   -- "arduino_language_server", -- written in 'go'
--   -- "asm_lsp", -- written in 'rust'
--   -- "ccls",
--   "clangd", -- requires a reasonably new version of glibc
--   "cmake",
--   -- "fortls", -- written in 'python'
--   -- "lemminx", -- XML Language Server written in 'java'
--   -- "ltex",
--   "marksman",
--   "prosemd_lsp",
--   -- "python-lsp-server",
--   -- "r_language_server", -- needs R in path
--   "lua",
--   -- "pyright"
--   -- "taplo", -- problematic with rust/cargo installs
--   -- "zk", -- link not found (404 error)
-- }

return M
