M = {}

M.kind_icons = {
  Text = "",
  -- Text = "",
  Method = "",
  Function = "",
  -- Constructor = "",
  Constructor = "",
  -- Field = " ",
  Field = "ﰠ",
  -- Variable = " ",
  Variable = "",
  -- Variable = "",
  -- Class = " ",
  -- Class = "",
  Class = "ﴯ",
  Interface = "",
  -- Interface = " ",
  -- Module = " ",
  Module = "",
  -- Property = " ",
  Property = "",
  -- Unit = " ",
  Unit = "塞",
  -- Value = " ",
  Value = "",
  -- Enum = " ",
  Enum = "",
  -- Keyword = " ",
  Keyword = "",
  -- Snippet = " ",
  Snippet = "",
  -- Color = " ",
  Color = "",
  -- File = " ",
  File = "",
  -- Reference = " ",
  -- Reference = "",
  Reference = "",
  -- Folder = " ",
  Folder = "",
  -- EnumMember = " ",
  EnumMember = "",
  -- Constant = " ",
  -- Constant = "",
  -- Constant = "",
  Constant = "",
  -- Struct = " ",
  Struct = "פּ",
  -- Struct = "" ,
  -- Event = " ",
  Event = "",
  -- Operator = " ",
  Operator = "",
  -- TypeParameter = " ",
  TypeParameter = "",
}

M.lsp_servers = {
  "clangd", -- requires a reasonably new version of glibc
  "cmake",
  "fortls",
  -- "ltex",
  "marksman",
  "prosemd_lsp",
  "pylsp",
  -- "r_language_server", -- needs R in path
  "sumneko_lua",
  -- "pyright"
  -- "taplo", -- problematic with rust/cargo installs
  -- "zk", -- link not found (404 errror)
}

return M
