M = {}

M.kind_icons = {
  -- Text = "",
  Text = "",
  -- Text = "",
  Method = "",
  Function = "",
  -- Constructor = "",
  Constructor = "",
  -- Field = " ",
  -- Field = "",
  Field = "ﰠ",
  -- Variable = " ",
  Variable = "",
  -- Variable = "",
  -- Class = " ",
  -- Class = "",
  -- Class = "",
  Class = "ﴯ",
  -- Interface = "ﰮ",
  -- Interface = " ",
  Interface = "",
  -- Module = " ",
  -- Module = "",
  Module = "",
  -- Property = " ",
  -- Property = "",
  Property = "",
  -- Unit = " ",
  -- Unit = "",
  Unit = "塞",
  -- Value = " ",
  Value = "",
  -- Enum = " ",
  Enum = "了",
  -- Enum = "",
  -- Keyword = " ",
  -- Keyword = "",
  Keyword = "",
  -- Snippet = " ",
  Snippet = "",
  -- Color = " ",
  -- Color = "",
  Color = "",
  -- File = " ",
  File = "",
  -- File = "",
  -- Reference = " ",
  -- Reference = "",
  Reference = "",
  -- Folder = " ",
  Folder = "",
  -- Folder = "",
  -- EnumMember = " ",
  EnumMember = "",
  -- Constant = " ",
  -- Constant = "",
  -- Constant = "",
  -- Constant = "",
  Constant = "",
  -- Struct = " ",
  -- Struct = "",
  Struct = "פּ",
  -- Struct = "" ,
  -- Event = " ",
  -- Event = "",
  Event = "",
  -- Operator = " ",
  Operator = "",
  -- TypeParameter = " ",
  -- TypeParameter = "",
  TypeParameter = "",
}

M.lsp_servers = {
  -- "arduino_language_server", -- written in 'go'
  -- "asm_lsp", -- written in 'rust'
  "ccls",
  "clangd", -- requires a reasonably new version of glibc
  "cmake",
  -- "fortls", -- written in 'python'
  -- "lemminx", -- XML Language Server written in 'java'
  -- "ltex",
  "marksman",
  "prosemd_lsp",
  "pylsp",
  -- "r_language_server", -- needs R in path
  "sumneko_lua",
  -- "pyright"
  -- "taplo", -- problematic with rust/cargo installs
  -- "zk", -- link not found (404 errror)
}

return M
