return {
  -- {
  --   "https://codeberg.org/esensar/nvim-dev-container", -- Neovim dev container support - Mirror of https://codeberg.org/esensar/nvim-dev-container
  --   lazy = false,
  --   config = function()
  --     require("devcontainer").setup {
  --       attach_mounts = {
  --         neovim_config = {
  --           enabled = true,
  --           options = { "readonly" },
  --         },
  --         neovim_data = {
  --           enabled = false,
  --           options = {},
  --         },
  --         -- Only useful if using neovim 0.8.0+
  --         neovim_state = {
  --           enabled = false,
  --           options = {},
  --         },
  --       },
  --     }
  --   end,
  -- },
  -- {
  --   "jamestthompson3/nvim-remote-containers",
  --   lazy = false,
  -- },
}
