-- vim: ft=lua:
-- overrides `require("mason-tool-installer").setup(...)`
return {
  ensure_installed = {
    -- "actionlint",
    -- "black",
    -- "cbfmt",
    -- "clang-format",
    -- "cmakelang",
    -- "codelldb",
    -- "codespell",
    -- "debugpy",
    -- "editorconfig-checker",
    -- "fixjson",
    -- "flake8",
    -- "gitlint",
    -- "hadolint",
    -- "luacheck",
    -- "misspell",
    -- "mypy",
    -- "proselint",
    -- "pylint",
    -- "shellcheck",
    -- "shfmt",
    -- "stylua",
    -- "vale",
    -- "vint",
    -- "vulture",
    -- "yamlfmt",
    -- "yamllint",
  },
  auto_update = true,
}
