return {
  ensure_installed = {
    "alex",
    "autoflake",
    "beautysh",
    "black",
    "cbfmt",
    "checkmake",
    "clang-format",
    "cmakelang",
    "codespell",
    "commitlint",
    "cppcheck",
    "cpplint",
    "cspell",
    "editorconfig-checker",
    "fixjson",
    "gersemi",
    "gitlint",
    "hadolint",
    "jq",
    "jsonlint",
    "markdownlint",
    "mdformat",
    "mypy",
    "proselint",
    "pycodestyle",
    "pydocstyle",
    "pylama",
    "pylint",
    "pyproject-flake8",
    "remark-cli",
    "reorder-python-imports",
    "ruff",
    "selene",
    "semgrep",
    "shellcheck",
    "shfmt",
    "stylua",
    "taplo",
    "textlint",
    "usort",
    "vint",
    "write-good",
    "yamlfmt",
    "yamllint",
    -- "actionlint",
    -- "ansiblelint",
    -- "buf",
  },
  automatic_installation = true,
  automatic_setup = false,
}
