return {
  after = "nvim-treesitter",
  ft = {
    "c",
    "cpp",
    "foam",
    "go",
    "javascript",
    "julia",
    "lua",
    "php",
    "python",
    "r",
    "ruby",
    "rust",
    "scss",
    "typescript",
  },
  -- config = function() require "user.plugins.nvim-treesitter-textsubjects.config" end,
}
